name: 'Path Tag Bump'
description: 'Create a new tag based on the path of the changed files'
inputs:
  service-name:  # id of input
    description: 'The name of the service that need a tag bump'
    required: true
    default: ''
  initial-version:  # id of input
    description: 'The initial version'
    required: true
    default: '1.0.0'
  tag_name:  # id of input
    description: 'The name of the tag'
outputs:
  new-tag: # id of output
    description: 'The version tag that is granted for the service'
runs:
  using: 'node16'
  main: 'dist/index.js'