name: 'Path Tag Bump'
description: 'Create a new tag based on the path of the changed files'
inputs:
  service-name:  # id of input
    description: 'The name of the service that need a tag bump'
    required: true
    default: ''
outputs:
  new-tag: # id of output
    description: 'The version tag that is granted for the service'
runs:
  using: 'node16'
  main: 'dist/index.js'