on: [push]

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    name: Path Tag Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ github.ref_name }}
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: 'customer'
#      - name: show tag
#        run: echo "the new tag is ${{ steps.pathtagbump.outputs.new-tag  }}"
